EBIvariation/CMAT

eva_cttv_pipeline/consequence_type.py
Changed method of opening file.
=> Chaged method of file opening

eva_cttv_pipeline/consequence_type.py
Pipeline was run to completion with no errors
=> SoTerm class removed from inside ConsequenceType class.

README.md
Added travis and coveralls markdown badges to README. For master branch.
=> Added travis and coveralls badges

.gitignore, README.md, eva_cttv_pipeline/config.py, eva_cttv_pipeline/efo_term.py, eva_cttv_pipeline/private_config.py
Private config file, left blank in repository, for CTTV sparql login details.
=> Private config

bin/gene_mapping/gene_map_coords.py
- Changed variant coordinate file generation to give to OT for gene mapping generation
- Removed strand from output
- Split reference and alternate alleles into separate columns
=> EVA-576 Changed coordinate generation for OT

bin/gene_mapping/gene_map_coords.py
Added strand back into coordinates file.
=> EVA-576 Added strand back into coordinates file.

bin/gene_mapping/gene_map_coords.py
Changes to the script that generates the coordinate file that Open Target use to generate affected gene/consequence types.
=> EVA-576 Changes to coordinate file script

eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_strings.py, requirements.txt
- json_schema submodule version updated
- disease name and source_name change to string
- progress bar
=> EVA-703 : Update Open Targets pipeline for new json schema version 1.2.5

eva_cttv_pipeline/clinvar.py, eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_strings.py, eva_cttv_pipeline/resources/CTTVGeneticsEvidenceString.json, eva_cttv_pipeline/resources/CTTVSomaticEvidenceString.json, eva_cttv_pipeline/utilities.py, tests/test_clinvar.py
- Updated json schema submodule
- Updated version in evidence string skeletons
- Added clinical_significance to evidence string classes
=> EVA-740 Update Open Targets pipeline for schema with clinical significance

bin/gene_mapping/gene_map_coords.py
Added allowed clinical significances to coordinate outputting
=> EVA-739 Generate coordinate list for Open Target

bin/clinvar_jsons/parse_trait_names.py, bin/trait_mapping/traits_to_zooma.py
Ontology xrefs from Clinvar output in trait mapping file, to make curation more efficient.
=> Clinvar xrefs in trait mappings

bin/clinvar_jsons/clinvar_jsons_shared_lib.py, bin/clinvar_jsons/extract_pathogenic_and_likely_pathogenic_variants.py, bin/clinvar_jsons/parse_trait_names.py, bin/clinvar_jsons/traits_to_zooma_format.py
- Branches from the branch of this PR https://github.com/EBIvariation/eva-cttv-pipeline/pull/39 so this should be merged first.
- Script to parse trait names and ontology xrefs from ClinVar records
=> EVA-807 Parse trait xrefs from ClinVar records into Zooma file format

README.md
- python3.4 to 3.5 in instruction
- removed unused sparql details instruction
=> EVA-825 OpenTargets coding training session : README update

requirements.txt
Added progressbar2 to requirements
=> EVA-825 Requirements file update (OpenTargets coding training session)

eva_cttv_pipeline/evidence_string_generation/clinvar.py, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py
Support for 'measureSet' nested under 'genotypeSet' during evidence string generation.
Logging added to report progress on the evidence string generation every 1000 records.
=> EVA-1076 Changes for generation of evidence strings for batch 18.02

bin/trait_mapping/validation_trait_mapping_pipeline.sh, eva_cttv_pipeline/validations/validation_trait_mapping_pipeline.sh
Initial version of the script, it works but needs some work (ie. refactor and not generating unnecessary files)
=> EVA-1448 Script for validating the trait mapping pipeline

README.md, bin/trait_mapping/create_table_for_manual_curation.py
* Reuse information about previous manual curations
* Output data for the new format of the manual curation table
=> EVA-1472 — Implemented new manual curation protocol

bin/trait_mapping/create_efo_table.py, bin/trait_mapping/create_table_for_manual_curation.py, tests/trait_mapping/test_create_efo_table.py
Implemented a script to generate a table for EFO import automatically. For every given term, it fills out: disease name, description (if available), parent term(s), synonym(s), database cross-refs.
=> EVA-1519 — Automate preparing terms for EFO import

docs/submit-opentargets-batch.md
Slight changes & clarifications in light of the recent ZOOMA file name change
=> EVA-1538 — Update documentation for ZOOMA feedback

bin/trait_mapping/create_table_for_manual_curation.py, docs/build.md, docs/manual_curation.md, docs/submit-opentargets-batch.md, eva_cttv_pipeline/trait_mapping/main.py
* Bug fix: run failure due to incorrect `ProgressBar` initialisation
* Update output format for the new improved layout of the manual curation table
* Log start and end of work to avoid the impression of the script getting stuck
* Documentation updates
+ Updated all processing commands for compatibility with LSF directory structure. Now there's no need to modify each command before running it; this will also ensure that all required output files will get stored on the cluster with consistent names.
+ Added link to the curation table template
+ Improved wording
=> EVA-1602 — improvements to documentation & processing commands

docs/submit-opentargets-batch.md
Instead of the general description, provided specific commands to release files on the FTP and check that the protocol has been successful.
=> EVA-1605 — Include specific commands to submit ZOOMA feedback

docs/submit-opentargets-batch.md
The diff might be a bit confusing so you can just see how this section looks after the rewrite: https://github.com/tskir/eva-cttv-pipeline/blob/eva-1702-zooma-docs-update/docs/submit-opentargets-batch.md#step-6-submitting-feedback-to-zooma-issue-template
As usual, rewrote commands for better automation & clarified some wording. Now actions are clearly grouped in three sections:
- Generate ClinVar xRefs
- Upload all necessary files to the FTP in a single completely automated block
- Check that the upload was successful with the checksums
=> EVA-1702 — Update ZOOMA submission docs for more clarify

bin/traits_to_zooma_format.py, docs/generate-evidence-strings.md, docs/manual-curation/step1-fetch-clinvar-data.md, eva_cttv_pipeline/clinvar_xml_utils.py, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/trait_mapping/trait_names_parsing.py, setup.py, vep-mapping-pipeline/run_consequence_mapping.sh
=> EVA-2342 — Test drive and complete version 2.0.0

eva_cttv_pipeline/trait_mapping/oxo.py, tests/trait_mapping/test_oxo.py
Fixes for new OMIM URI format, as uncovered during #223.
=> fix for new omim uri format

eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, tests/eva_cttv_pipeline/evidence_string_generation/test_clinvar_to_evidence_strings.py
=> Issue 237 - Report evidence regardless of ontology mapping status

eva_cttv_pipeline/clinvar_xml_utils.py, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, tests/eva_cttv_pipeline/evidence_string_generation/test_clinvar.py, tests/eva_cttv_pipeline/evidence_string_generation/test_clinvar_to_evidence_strings.py
=> Issue 222 - Improvements to allele origin reporting

consequence_prediction/repeat_expansion_variants/biomart.py
=> Catch biomart errors that come back as 200s

docs/generate-evidence-strings.md
=> Issue 246 - Update documentation for evidence string generation

docs/generate-evidence-strings.md
Closes https://github.com/EBIvariation/eva-opentargets/issues/261
=> ISSUE-261 - Added variantId to the uniqueness tuple

data-exploration/complex-events/notebooks/detailed-hgvs-stats.ipynb, data-exploration/complex-events/notebooks/hgvs-follow-up.ipynb
View notebook [here](https://notebooks.githubusercontent.com/view/ipynb?commit=a04421a2ac3046a19aba68a4e53a56c16465ece2&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f617072696c747565736461792f6576612d6f70656e746172676574732f613034343231613261633330343661313961626136386134653533613536633136343635656365322f646174612d6578706c6f726174696f6e2f636f6d706c65782d6576656e74732f6e6f7465626f6f6b732f64657461696c65642d686776732d73746174732e6970796e62&logged_in=true&nwo=apriltuesday%2Feva-opentargets&path=data-exploration%2Fcomplex-events%2Fnotebooks%2Fdetailed-hgvs-stats.ipynb).
=> Detailed HGVS stats notebook

eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py
=> Add number of structural variants to metrics

docs/manual-curation/step2-manual-curation.md
Curation documentation update adding detail for 
- Filtering and remapping any EFO_OBSOLETE terms
- Prioritizing non-EFO exact match over sub->parent 
- Format for adding comments
=> Step2 doc updated

consequence_prediction/repeat_expansion_variants/pipeline.py, consequence_prediction/vep_mapping_pipeline/consequence_mapping.py
* Don't count non-microsatellites in repeat pipeline
* Cache severity ranking
=> Minor fixes following 2023.06 submission
