eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_strings.py, tests/test_evidence_strings.py
-Moved reporting to different 
-Fixed calls to superclasses and changed super of CTTVEvidenceString from UserDict back to dict
-Tests for validate functions
-Calls to "super" rather than explicitly mentioning class
=> Extract reporting

eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/config.py, eva_cttv_pipeline/efo_term.py, eva_cttv_pipeline/evidence_strings.py, eva_cttv_pipeline/utilities.py
- Moved cellbase and output configuration to config.py
- Moved evidence_strings settings to config file. 
- Moved references to config variables from top of files, to where they're used.
=> Centralise config

bin/clinvar_jsons/parse_trait_names.py, eva_cttv_pipeline/clinvar.py, eva_cttv_pipeline/clinvar_to_evidence_strings.py
- Don't exclude "not provided" trait values
- Only get region ids from dbvar/dgva
- Don't skip records with same ref and alt, might be SV etc
=> Changes made to pipeline during February 2017 OpenTargets batch

eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/resources/CTTVGeneticsEvidenceString.json, eva_cttv_pipeline/resources/CTTVSomaticEvidenceString.json
Original PR found here: https://github.com/EBIvariation/eva-cttv-pipeline/pull/34
Changed the version numbers on the template json files and updated the json_schema submodule.
=> EVA-703 : Update Open Targets pipeline for new json schema version 1.2.5 - PART 2

eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/trait.py, tests/resources/feb16_jul16_combined_trait_to_url.tsv, tests/test_clinvar_to_evidence_strings.py
Trait mapping file allowed to have multiple mappings for one trait, e.g.:
coronary artery disease/myocardial infarction http://www.ebi.ac.uk/efo/EFO_0000612 | http://www.ebi.ac.uk/efo/EFO_0001645 myocardial infarction|coronary heart disease
each column separated by a pipe character. There are now one evidence string per ontology mapping.
=> EVA-707 Allow multiple mappings for single traits in OT pipeline

bin/trait_mapping/traits_to_zooma.py, eva_cttv_pipeline/clinvar_to_evidence_strings.py, eva_cttv_pipeline/config.py, eva_cttv_pipeline/consequence_type.py
This should hopefully solve the issue of duplicate entries in the zooma file. Rather than Gary creating the zooma file based upon the evidence records file a file is output ready for Zooma-consumption.
=> EVA-697 : Output zooma file from pipeline

eva_cttv_pipeline/evidence_string_generation/consequence_type.py, eva_cttv_pipeline/evidence_string_generation/resources/CTTVGeneticsEvidenceString.json, eva_cttv_pipeline/evidence_string_generation/resources/CTTVSomaticEvidenceString.json
Evidence string generation update for new Open Target data and schema
- Added trinucleotide_repeat_expansion to so_terms
- Updated jsons
- Updated json_schema submodule
=> EVA-872 Generate and submit evidence strings

bin/update_clinvar_schema.py
Delete previous version of the Java XML binding classes when generating them for a new Clinvar version
=> EVA-866 Replace Clinvar Java binding classes if they exist

eva_cttv_pipeline/trait_mapping/oxo.py
Our code is now able to report when the OxO API doesn't return a response at all, or the response is not well formed. Before it was failing during the processing due the lack on an `_embedded` JSON object.
=> EVA-1222 Improve resiliency when OxO API returns errors

bin/trait_mapping.py, eva_cttv_pipeline/__init__.py, eva_cttv_pipeline/trait_mapping/__init__.py, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/ols.py, eva_cttv_pipeline/trait_mapping/oxo.py, eva_cttv_pipeline/trait_mapping/utils.py, eva_cttv_pipeline/trait_mapping/zooma.py
* Fixed crash when Zooma returns an empty result set. The bug manifested itself when all results from Zooma for a given query had `is_defining_ontology = False` (such results are ignored). Although it happened for only a few records, a subroutine returned None, which was then propagated and the module crashed when trying to iterate over None. This is now fixed by returning `[]` instead of None; an appropriate warning message is issued in such a situation.
* Rewrote logging in `trait_mapping` to consistently use the `logging` module; all `print` calls used for logging purposes were removed.
* Added option `-u` for running the pipeline on the cluster. This disables ETA outputs, which were clogging the logs by thousands of lines.
=> EVA-1471 — Bugfix for empty Zooma result, improved logging

README.md, bin/clinvar_jsons/traits_to_zooma_format.py, bin/trait_mapping.py, bin/trait_mapping/traits_to_zooma.py, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/ols.py, eva_cttv_pipeline/trait_mapping/output.py, eva_cttv_pipeline/trait_mapping/oxo.py, eva_cttv_pipeline/trait_mapping/trait.py, eva_cttv_pipeline/trait_mapping/zooma.py, tests/trait_mapping/test_output.py, tests/trait_mapping/test_oxo.py, tests/trait_mapping/test_trait_names_parsing.py
* Ontology terms from MONDO are now supported and added to the output where appropriate.
* Added support on how to deploy a local OLS server and how to use it.
* When mappings are selected for manual curation, output those who are either present in EFO and not obsolete, or not present in EFO at all. (Previously: only non-obsolete EFO mappings were selected for curation.)
+ Added a field which contains a status of the record in relation to EFO (either `EFO_CURRENT` or `NOT_CONTAINED`).
+ Also updated tests `TestGetMappingsForCuration` and `TestOutputForCuration` to reflect the new logic.
* Further improved logging for debugging.
* Drop support for "human phenotype ontology", an obsolete OxO alias for HP.
=> EVA-1445 — Search in MONDO during automated trait mapping

clinvar-xml-parser/pom.xml, requirements.txt
* Remove `PyYAML` 3.11: dependency not used.
* Update `requests`: 2.9.1 → 2.20.0+. Compatibility of simple methods that we use, such as `get()` and `post()`, should not be affected.
* Update `com.fasterxml.jackson.databind`: 2.9.0 → 2.9.8. This is a patch update, compatibility should not be affected.
=> EVA-1483 — Update dependencies to mitigate vulnerabilities

clinvar-xml-parser/pom.xml, docs/build.md, docs/submit-opentargets-batch.md, requirements.txt
* Update batch submission documentation for increased automation & reproducibility
+ All environment variables are now defined and explained in one place
+ Added base bsub command and ability to configure e-mail notifications for a specific user
+ ClinVar file download and schema version determination are now automated
+ Increased memory limit for ClinVar parsing (due to increased file size, it started crashing just before finishing all the records)
* Synchronise jsonschema version with the one used in OT validator (so that we get the same results)
* Update jackson-databind version to 2.9.10 (patch update to mitigate security vulnerability)
=> EVA-1698 — Update documentation & commands for JSON generation

bin/clinvar_jsons/traits_to_zooma_format.py, bin/trait_mapping.py, docs/submit-opentargets-batch.md, eva_cttv_pipeline/evidence_string_generation/__init__.py, eva_cttv_pipeline/trait_mapping/__init__.py, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/ols.py, eva_cttv_pipeline/trait_mapping/oxo.py, eva_cttv_pipeline/trait_mapping/utils.py, eva_cttv_pipeline/trait_mapping/zooma.py, requirements.txt
* Refactor & code cleanup
+ Traits are now processed in parallel, increasing performance (approx. 8× boost, from 0.5 traits/s to 4 traits/s)
+ Simplify retry policy for `json_request`, remove unnecessary helpers. Now using an external `retry` library
+ Configure correct handling of different error types; do not ignore any request errors unless directly specified.
* Fixes for OxO queries
+ OxO requests now always use POST instead of GET
+ Do not try to query OxO when the identifier list is empty, as this causes predictable errors which show up in the logs
+ Correctly handle occasional OxO errors. There is a bug which I discovered and reported: https://github.com/EBISPOT/OXO/issues/26
* Logs cleanup
+ Remove double warning for the same error when OLS didn't return a term label
+ Don't show …
=> EVA-1700 — fixes to trait mapping pipeline

docs/manual-curation.md, docs/submit-opentargets-batch.md
Updated spreadsheet template for manual curation and documentation:
* Replaced the binary “Done/Not done” with the new "Status" column for more flexibility. Described the acceptable range of values for it in the documentation.
* Clarified how to add new mappings (as opposed to copy-pasting mappings suggested by the pipeline). Fixed formulas in the spreadsheet to correctly handle manually entered mappings.
* Empathised the importance of removing extra space symbols and line breaks in the manually entered terms. Implemented automatic validation in the spreadsheet.
* Following comment by @jmmut clarified how to set up environment for the manual curation protocol.
=> EVA-1701 — Update documentation for manual curation

bin/trait_mapping/create_efo_table.py, docs/submit-opentargets-batch.md, tests/trait_mapping/test_zooma.py
Previously OLS supported two kinds of queries: either by URI, e.g. `http://www.orpha.net/ORDO/Orphanet_425`, or by curie, e. g. `Orphanet:425`. Our calls were using curie format; now only URI format is supported. I adjusted documentation accordingly. No changes to the script itself are necessary.
Secondary change: when running builds for this PR, I discovered that the ZOOMA tests are failing. This is because the ClinVar has modified names for some traits. I have now chosen a different trait to do this test.
=> EVA-1744 — Update docs for generating EFO table

docs/compare-evidence-strings.md, docs/submit-opentargets-batch.md
The commands which I used to compare evidence strings may be useful in the future as well. I have compiled them into a separate document (compare-evidence-strings.md).
=> EVA-1845 — Added commands to compare evidence strings

docs/submit-opentargets-batch.md, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_string_generation/consequence_type.py
* **Integrated the repeat expansion pipeline**
+ Download the third file type from ClinVar, TSV summary.
+ Added commands to run the pipeline and to unite its results with the VEP pipeline.
+ Pair variants and consequences using RCV by default. This is done to avoid ingesting any incorrect mappings produced by VEP for the same variants using the coordinate notation. Added a comment with the detailed explanation.
+ Added `short_tandem_repeat_expansion` to the list of supported variant types.
+ Amended review checklist.
* **Other protocol adjustments**
+ Added commands to run the code for both main & VEP pipelines using arbitrary remote and branch—very useful for debugging purposes.
+ Revised commands to download ClinVar data so that FTP paths are correctly formed in all cases.
+ Added …
=> EVA-1938 — Integrate repeat expansion pipeline

eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py
Do not store all evidence strings in memory, output them as they are constructed.
=> EVA-1446 — Incremental writes to reduce memory usage during evidence string generation

docs/manual-curation/step1-fetch-clinvar-data.md, docs/manual-curation/step2-manual-curation.md, docs/manual-curation/step3-export-results.md, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/output.py, eva_cttv_pipeline/trait_mapping/trait.py, eva_cttv_pipeline/trait_mapping/trait_names_parsing.py, tests/trait_mapping/test_trait_names_parsing.py
* Prioritise traits which link to repeat expansion variants. Instead of number of records, they will just display a "NT expansion" in the frequency column. Also updated the protocol to reflect the importance of these traits.
* Lower threshold for trait occurrence from 10 to 5: as our protocols improve, we can and should curate more traits now.
* Count trait name frequency slighly more accurately, taking into account that a trait name can appear _multiple_ times in the same row for the same allele ID.
* Preserve all mappings from the previous iterations, even if they are not present in the latest ClinVar version use for manual curation.
=> EVA-1999 — Prioritise repeat expansion variant traits in manual curation

clinvar-variant-types/README.md, eva_cttv_pipeline/evidence_string_generation/clinvar.py
* Only handle isolated ClinVar records with isolated variants
* Mild cleanup of the clinvar.py module 
* Update documentation
Closes #127.
=> EVA-2090 — Ditch haplotype and genotype support

eva_cttv_pipeline/evidence_string_generation/resources/CTTVGeneticsEvidenceString.json, tests/evidence_string_generation/resources/expected_genetics_evidence_string.json
Closes #121.
Removes the gene2variant → resource_score section in the evidence strings which was added in August 2019 for compatibility with the updates in OT JSON schema. Since then, the schema was modified, making this field (with placeholder values) unnecessary and even detrimental. As per discussions with Asier, this will be removed.
@jmmut @tcezard The review required is not so much of the actual change, but of the discussion history in the Open Targets ticket: https://github.com/opentargets/platform/issues/1138
=> EVA-2019 — Remove the gene2variant resource_score

bin/trait_mapping/create_table_for_manual_curation.py, docs/generate-evidence-strings.md, docs/manual-curation/step1-fetch-clinvar-data.md, docs/manual-curation/step3-export-results.md, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_string_generation/config.py
* Move creation of the eva_clinvar dataset from evidence string generation to manual curation
* Move submitting eva_clinvar feedback to ZOOMA from evidence string generation to manual curation
* Use previous mappings directly instead of ZOOMA feedback files
Closes #137 (details of the issue are also described there).
=> EVA-2106 — Refactor approach to ZOOMA feedback

compare-evidence-strings/compare.sh, eva_cttv_pipeline/evidence_string_generation/clinvar.py, eva_cttv_pipeline/evidence_string_generation/evidence_strings.py, eva_cttv_pipeline/evidence_string_generation/resources/CTTVGeneticsEvidenceString.json, eva_cttv_pipeline/evidence_string_generation/resources/CTTVSomaticEvidenceString.json, tests/evidence_string_generation/resources/expected_genetics_evidence_string.json, tests/evidence_string_generation/resources/expected_somatic_evidence_string.json, tests/evidence_string_generation/test_clinvar.py
Closes #124. Built on top of #146 and includes all changes from it. More details: https://github.com/opentargets/platform/issues/1137.
The ClinVar star rating (from 0 to 4) and the review status (one of a few possible values) are now extracted from ClinVar and added to the evidence strings. Because of how evidence this represented (see https://github.com/opentargets/platform/issues/1137#issuecomment-663633967 and https://github.com/opentargets/platform/issues/1137#issuecomment-683728359), the values are only output for germline mutations. Further discussion with OT about this pending.
Also submitted a PR to improve the OT JSON schema, details: https://github.com/opentargets/json_schema/pull/96
Also also, fixed a memory leak & removed unnecessary code complexity in the evidence string …
=> Add ClinVar star rating and review status

clinvar-variant-types/clinvar-variant-types.py, eva_cttv_pipeline/evidence_string_generation/clinvar.py, eva_cttv_pipeline/evidence_string_generation/evidence_strings.py
Closes #123. This PR is built on top of #148 and includes all changes from it. See https://github.com/opentargets/platform/issues/1140 for more details.
Mode of inheritance, where present, is now parsed from ClinVar data and included into the evidence strings. This is only possible for `genetic_association` evidence strings and not for somatic mutations (see https://github.com/opentargets/platform/issues/1140#issuecomment-683861830). Importantly, there may be several modes of inheritance per ClinVar record, which is reflected in the code changes.
Also submitted a PR to adjust OT JSON schema, details over there: opentargets/json_schema/pull/97.
=> Include mode of inheritance

bin/traits_to_zooma_format.py, docs/generate-evidence-strings.md, docs/manual-curation/step2-manual-curation.md, docs/manual-curation/step3-export-results.md, eva_cttv_pipeline/clinvar_xml_utils.py, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_string_generation/consequence_type.py, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/trait_names_parsing.py, setup.py, tests/evidence_string_generation/test_clinvar.py
Version 2.0.1 addresses three groups of issues. Issues highlighted in bold contain substantial discussions and are recommended for reading.
* Closes EBIvariation/eva-opentargets#188. Updated commands and added duplicate checks in the manual curation protocol.
* Closes EBIvariation/eva-opentargets#178. Updated commands and added duplicate check in the evidence string generation protocol.
* **Closes EBIvariation/eva-opentargets#185.** Confirmed that all problems with duplication have now been resolved.
* Closes EBIvariation/eva-opentargets#192. Investigated the three types of ClinVar literature references (disease specific, trait specific, evidence support).
* **Closes EBIvariation/eva-opentargets#166.** Reported the results of literature reference analysis and confirmed that versions …
=> EVA-2343 — Version 2.0.1: Improvements in evidence string duplication, PubMed references, string-to-ontology mapping

eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py
Closes #159. Closes #211.
With versions v2.0.0 ... v2.0.2, several report metrics which are related to unmapped traits aren't working (#211):
* Number of unmapped traits, after filtering for allele origin and Ensembl gene mapping;
* ClinVar records with valid rs id and Variant->ENSG mapping skipped due to a lack of EFO mapping;
* Number of records with unmapped traits where traits were “not provided”, “not specified”, etc., or missing altogether;
* Percentage of ClinVar records for which at least one evidence string was generated, but exluding traits for which ontology mapping is impossible, e. g. “not provided”, “not specified”, etc., or missing altogether.
Also, with versions v1.3.* these metrics weren't quite reliable already, since some source ClinVar records appear to have been …
=> Fix metrics for unmapped traits in the report

.idea/dictionaries/ktsukanov.xml, bin/traits_to_zooma_format.py, eva_cttv_pipeline/clinvar_xml_utils.py, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/trait_mapping/main.py, eva_cttv_pipeline/trait_mapping/trait_names_parsing.py, tests/evidence_string_generation/test_clinvar.py
Unified the list of nonspecific trait names: things like “disease”, “not provided”, “not specified” etc.—in other words, something which cannot be _possibly_ mapped to anything sensible.
Based on this change, introduced two new concepts:
* `preferred_or_other_valid_name` is a sensible, consistent name for a given ClinVarTrait. It works like this:
+ If there is a preferred name, and it's not in the blacklist of nonspecific names, use that one;
+ Otherwise, if there are any other (non-preferred) names which are not in the blacklist, use the first one alphabetically;
+ Otherwise, return None.
* Consequently, `traits_with_valid_names` of a ClinVarRecord contains the list of only those traits which have `preferred_or_other_name` defined.
Completely refactored the reporting system and [**the …
=> EVA-2378 — Refactor the quality control system

eva_cttv_pipeline/clinvar_xml_utils.py
The ontology URIs in `clinvar-xrefs.txt` had spaces in them incorrectly. From looking at the code I think this must be because of extra whitespace in the clinvar XML data. To solve this problem, strip any leading or trailing whitespace from the ontology ID so that when we combine it with the URI for that ontology, there should not be any spaces in the middle.
Fixes #215.
=> ISSUE-215: strip white spaces from ontology identifiers

docs/build.md, docs/generate-evidence-strings.md
Closes #203.
Modified the README containing the protocols to generate evidence strings:
* Replaced the previous command with the new one, stricter, that checks for the 5 repeated fields. I used `Positive LookBehind` and regex with `grep`  for this, since I could not find a `JSON` parser within ``noah-login-02``. 
* Added what we consider a duplicated evidence string within the same README. If you feel like this documentation should not be within the protocol, let me know where to place it: duplication of evidence strings was not mentioned elsewhere.
=> ISSUE-203 - Duplication checks and documentation

docs/generate-evidence-strings.md
Closes #248.
Added the field ``diseaseFromSource`` to the ones used to check for duplicates, solving the issue of non-duplicated evidence strings being considered as so when field ``diseaseFromSourceMappedId`` was missing. Also updated the documentation.
This second pull request of the same branch (first one is [here](https://github.com/EBIvariation/eva-opentargets/pull/254)) was created due to an error in the checks that is supposed to be fixed already.
=> ISSUE-248 - Added field diseaseFromSource to check for duplicates

compare-evidence-strings/README.md, compare-evidence-strings/compare.sh
Closes #201.  The comparison tool is now usable (and useful) for the new evidence string format, I think there are more improvements to be made but this should be a good start.
=> Issue-201: update evidence string comparison for v2 JSON schema

consequence_prediction/vep_mapping_pipeline/severity_ranking.txt
The [original documentation](https://m.ensembl.org/info/genome/variation/prediction/predicted_data.html) has not been updated so I had to guess if the more specific consequence (splice_donor_5th_base_variant) were placed above or bellow the more general ones (splice_donor_variant).
For now I have preferred to set them bellow to ensure continuity of results. But that could be changed now or latter.
closes #296
=> Add splicing variant consequence to severity_ranking.txt

bin/evidence_string_generation.py, consequence_prediction/run_structural_variants.py, consequence_prediction/structural_variants/pipeline.py, docs/build.md, docs/environment.md, docs/generate-evidence-strings.md, eva_cttv_pipeline/evidence_string_generation/clinvar_to_evidence_strings.py, eva_cttv_pipeline/evidence_string_generation/consequence_type.py, eva_cttv_pipeline/evidence_string_generation/pipeline.nf, setup.py, tests/eva_cttv_pipeline/evidence_string_generation/config.py, tests/eva_cttv_pipeline/evidence_string_generation/resources/expected_genetics_evidence_string.json, tests/eva_cttv_pipeline/evidence_string_generation/resources/expected_multiple_names_evidence_string.json, tests/eva_cttv_pipeline/evidence_string_generation/resources/expected_somatic_evidence_string.json, tests/eva_cttv_pipeline/evidence_string_generation/test_clinvar_to_evidence_strings.py, tests/eva_cttv_pipeline/evidence_string_generation/test_consequence_type.py
The evidence string generation protocol is now contained entirely within a Nextflow pipeline!  There's basically a 1-to-1 correspondence between processes in the Nextflow and steps from the original SOP, both to make the initial implementation as straightforward as possible and to make it easier to review.  Some notes:
* Removed the `include_structural` param (it was just for testing, we're always running the structural pipeline now)
* The consequence prediction pipelines (SNP/indels (formerly called "VEP", which was a bit misleading), repeat expansion, and structural) now operate in parallel from the Nextflow.  Internally the functionality is unchanged.
* Updated documentation/SOP
Successfully tested locally and in the cluster, see `${BATCH_ROOT_BASE}/batch-2022-08_test`.
@M-casado, feel …
=> Convert evidence string generation to Nextflow

README.md, docs/manual-curation/step1-fetch-clinvar-data.md, docs/manual-curation/step3-export-results.md, docs/open-targets/generate-evidence-strings.md, pipelines/annotation_pipeline.nf, pipelines/export_curation_spreadsheet.nf, pipelines/generate_curation_spreadsheet.nf, pipelines/nextflow.config, setup.py, tests/output_generation/evaluation/test_ols_utils.py, tests/output_generation/test_pipeline.sh
* Option to download the latest released version rather than git clone
* Environment variables - reduced to just one required and put in config file
* Instructions to check installation with test dataset
=> Update installation instructions

bin/trait_mapping/create_table_for_manual_curation.py, cmat/trait_mapping/ols.py, cmat/trait_mapping/ontology_uri.py, cmat/trait_mapping/oxo.py, docs/manual-curation/step2-manual-curation.md
Closes #402 - updates to replacement terms and manual curation SOP
Based on automated-mappings branch, see diff [here](https://github.com/apriltuesday/eva-opentargets/compare/automated-mappings...issue-402)
=> Issue 402: Manual curation fixes from October

cmat/output_generation/clinvar_to_evidence_strings.py
This should properly count RCVs that only generate invalid evidence as skipped.
=> Modify counts for when evidence is invalid

bin/aggregate_counts.py, bin/count_clinvar_rcvs.py, bin/evidence_string_generation.py, cmat/clinvar_xml_io/clinvar_record.py, cmat/output_generation/clinvar_to_evidence_strings.py, cmat/output_generation/report.py, pipelines/annotation_pipeline.nf, requirements.txt, tests/output_generation/test_clinvar_to_evidence_strings.py, tests/output_generation/test_report.py, tests/pipelines/test_annotation_pipeline.sh
=> Issue 416 - Parallelise evidence string generation

docs/manual-curation/step2-manual-curation.md
Can be viewed [here](https://github.com/apriltuesday/eva-opentargets/blob/EVA-3887/docs/manual-curation/step2-manual-curation.md)
The major updates are adding a description of the mapping string, and a re-write of the curation workflow to make it (hopefully) simpler and more aligned with current practice. Please have a read of this bit in particular to make sure it makes sense.
Closes #471
=> EVA-3887: Update manual curation SOP
